### ISSUE TITLE
Error: Unknown KV type 48 encountered at offset 7

### ISSUE THREAD

**Issue by protzi** [DoctorMcKay/node-binarykvparser#2]
After update to v 2.1.1, got this error
this happens after loggedOn event
and
```
client.steamID.getSteam3RenderedID()
client.setPersona(SteamUser.EPersonaState.Online);
client.gamesPlayed(730); 
```
error:  Error: Unknown KV type 48 encountered at offset 7
    at Object.exports.parse (/home/path_to/binarykvparser/index.js:73:11)
    at /home/path_to/node_modules/steam-user/components/apps.js:116:36
    at Array.forEach (native)
    at /home/path_to/steam-user/components/apps.js:112:26
    at Object.cb (/path_to/steam-user/components/messages.js:152:4)
    at CMClient._netMsgReceived (/home/path_to/steam-client/lib/cm_client.js:276:26)
    at CMClient.handlers.(anonymous function) (/home/path_to/steam-client/lib/cm_client.js:386:8)
    at CMClient._netMsgReceived (/home/path_to/steam-client/lib/cm_client.js:260:24)
    at emitOne (events.js:96:13)
    at TCPConnection.emit (events.js:188:7)
    at TCPConnection._readPacket (/home/path_to/steam-client/lib/tcp_connection.js:73:7)
    at emitNone (events.js:86:13)
    at TCPConnection.emit (events.js:185:7)
    at emitReadable_ (_stream_readable.js:432:10)
    at emitReadable (_stream_readable.js:426:7)
    at readableAddChunk (_stream_readable.js:187:13)

**Comment by DoctorMcKay** [comment]
I don't have time right now to troubleshoot this, so I'm going to go ahead and re-publish v2.1.0 as v2.1.2.

**Comment by Cohedrin** [comment]
Are you able to provide a binary reproducing this @protzi? I've run this against every file here: https://github.com/SleepProgger/Binary-vdf-test-data, but I was unable to get it to error. I'm also not seeing that error happen when logging into steam myself using that version of the kv parser.

Looking at the line that stack trace is referencing [this example file](https://github.com/DoctorMcKay/node-steam-user/blob/master/examples/databasedownloader.js) should reproduce the issue, as it seems to be happening from a call [here](https://github.com/DoctorMcKay/node-steam-user/blob/master/components/apps.js#L113), but im unable to reproduce it with that script, or by simply logging and and using those lines you pasted above.

Are you perhaps on an old version of steam-client? That shouldn't be causing the issue, but knowing the version you're on will help me narrow down where the issue is coming from

**Comment by Cohedrin** [comment]
@protzi Here's a reproduction script for it: https://github.com/Cohedrin/steam-bot-bin-test.

If you pull this and run, you shouldn't get any errors (this is locked to use 2.1.1).

If you do get errors, please provide steps to reproduce. 

If you don't could you fork it and add the function calls that your code uses until it causes the error? I suspect there's something else going on here, but I'm not sure what it is
